[package]
name = "alltopics"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
# added on tutorial
[dependencies]
humantime = "2.1.0"
chrono = "0.4.38"
